---
- user: root
  hosts: dns-master
  gather_facts: no
  tasks:
  - name: update dns-infrastructure git repo
    git: repo=git@bitbucket.org:staticsafe/dns-infrastructure.git dest=/etc/namedb/dns-infrastructure update=yes
  - name: ensure permission correctness
    file: /etc/namedb/dns-infrastructure owner=bind group=bind state=directory recurse=yes
    notify:
    - reload nameserver daemon
  handlers:
    - name: reload nameserver daemon
      action: service name=named state=reloaded
