---

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

- name: apply configuration to web servers (nginx)
  hosts: webservers
  user: root

  roles:
    - webservers-nginx
